services:
  db:
    image: mysql
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: 'web'
      MYSQL_PASSWORD: 'flash007'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/code
    depends_on:
      - db
 